version: '3'

services:
  server-php:
    image: aeondigital/engarde-php7.4-apache-mysql:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    links:
      - db


  db:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=docker-db
      - MYSQL_USER=docker-user
      - MYSQL_ROOT_PASSWORD=docker-passw
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
