version: '3'

services:
  server-apache-php:
    image: aeondigital/engarde-apache-php-7.4
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    links:
      - db


  server-db-mysql:
    image: mysql:8.0.27
    container_name: engarde-server-db-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=docker-db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=docker-root-passw
      - MYSQL_USER=docker-user
      - MYSQL_PASSWORD=docker-user-passw
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
