version: '3'

#
# Volumes gerenciados pelo Docker para uso
# nos demais serviços.
volumes:
  server-db-mysql-data:

#
# Descrição dos serviços
services:

  # 
  # Servidor Apache com PHP 7.4
  server-apache-php:
    image: aeondigital/engarde-apache-php-7.4:0.9.19a5e31
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/html
    links:
      - server-db-mysql


  #
  # Servidor de banco de dados MySQL 8.0
  server-db-mysql:
    container_name: server-db-mysql
    image: mysql:8.0.27
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    env_file:
      - ./services/db-server/mysql-8.0/env/mysql.env
    volumes:
      - server-db-mysql-data:/var/lib/mysql  